[project]
name = "ftbatch-bulk-edit"
version = "0.2.1" # removed for dynamic versions
# dynamic = ["version"]
authors = [
  { name = "Marcelo Amorim", email = "marcelo.amorim@wmeng.com" },
  { name = "Dan Nguyen", email = "dan.nguyen@wmeng.com" },
]
description = "FactoryTalk Batch Bulk Editor"
readme = "README.md"
requires-python = ">=3.14,<3.15"
dependencies = [
    "lxml>=6.0.2",
    "openpyxl>=3.1.5",
    "toml>=0.10.2",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pre-commit>=4.5.1",
    "pydantic>=2.12.5",
    "pytest>=8.3.4",
]

[tool.pytest.ini_options]
pythonpath = [
    "app" # the pytests can import modules from this folder
]

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver"
version_provider = "pep621"
update_changelog_on_bump = true
major_version_zero = true

# [semantic_release.branches.main]
# match = "(main|master)"
# prerelease_token = "rc"
# prerelease = false


# ! Build related tables

# [tool.uv-dynamic-versioning]
# vcs = "git"
# style = "semver"

# [build-system]
# requires = ["hatchling", "uv-dynamic-versioning"]
# build-backend = "hatchling.build"

# [tool.hatch.version]
# source = "uv-dynamic-versioning"

# [tool.hatch.build.hooks.uv-dynamic-versioning]
# version-file = "_version.py"
